### ISSUE TITLE
Firefox issue: `navigator.clipboard.readText is not a function`

### ISSUE THREAD

**Issue by thanhnguyen2187** [thanhnguyen2187/crypta#47]
![image](https://github.com/thanhnguyen2187/crypta/assets/27758849/35b618a7-f782-4ed3-99b4-3fab9f1aaf05)

**Comment by thanhnguyen2187** [comment]
It might conflict with #46, where we also want to paste an image sometimes.

Solution: add the "holding down" interaction to the add snippet button.
